vich_uploader:
    db_driver: orm

    mappings:
       services:
           uri_prefix: /images/services
           upload_destination: '%kernel.project_dir%/public/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       habitats:
           uri_prefix: /images/habitats
           upload_destination: '%kernel.project_dir%/public/images/habitats'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       savane:
           uri_prefix: /images/animaux/savane
           upload_destination: '%kernel.project_dir%/public/images/animaux/savane'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       marais:
           uri_prefix: /images/animaux/marais
           upload_destination: '%kernel.project_dir%/public/images/animaux/marais'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       jungle:
           uri_prefix: /images/animaux/jungle
           upload_destination: '%kernel.project_dir%/public/images/animaux/jungle'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
